=== francesccapllonchPauCasesNoves/TascaFinal/dades/activitats.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--  Esquema XSD per validar el fitxer activitats.xml -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="activitats">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="activitat" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="id" type="xs:string"/>
                        <xs:element name="titol" type="xs:string"/>
                        <xs:element name="descripcio" type="xs:string"/>
                        <xs:element name="data" type="xs:string"/>
                        <xs:element name="categoria">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="nomCat" type="xs:string"/>
                                    <xs:element name="color" type="xs:string"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>

                        <xs:element name="prioritat">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="nom">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="Alta"/>
                                                <xs:enumeration value="Mitjana"/>
                                                <xs:enumeration value="Baixa"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:element>
                                </xs:sequence>
                                <xs:attribute name="tipus" type="xs:string" use="required"/>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="realitzada" type="xs:string"/> 
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>


</xs:schema>

=== francesccapllonchPauCasesNoves/TascaFinal/dades/activitats_001.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--  Copia de activitats001.json pero amb format xml-->

<activitats xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
            xsi:noNamespaceSchemaLocation="activitats.xsd">
    
    <activitat>
        <id>task-001</id>
        <titol>Crea l'estructura de carpetes del projecte</titol>
        <descripcio>Organitza els fitxers: HTML, CSS, JS, dades...</descripcio>
        <data >2025-04-15</data>
        <categoria>
            <nomCat>Organització</nomCat>
            <color>#f7df1e</color>
        </categoria>
        <prioritat tipus = "alta" >
                <nom>Alta</nom>
        </prioritat>
        <realitzada>false</realitzada>
    </activitat>
    <activitat>
        <id>task-002</id>
        <titol>Diseny la interfície d'index</titol>
        <descripcio>Mostrar llista de tasques</descripcio>
        <data >2025-04-16</data>
        <categoria>
            <nomCat>Disseny</nomCat>
            <color>##e5989b</color>
        </categoria>
        <prioritat tipus = "mitjana" >
                <nom>Mitjana</nom>
        </prioritat>
        <realitzada>false</realitzada>

    </activitat>
    <activitat>
        <id>task-003</id>
        <titol>Implementa el formulari a crear-tasca.html</titol>
        <descripcio>Inclou validació dels camps i guardat a localStorage.</descripcio>
        <data >2025-04-17</data>
        <categoria>
            <nomCat>Formularis</nomCat>
            <color>#6c5ce7</color>
        </categoria>
        <prioritat tipus = "alta" >
                <nom>Alta</nom>
        </prioritat>
        <realitzada>false</realitzada>
        
    </activitat>
    <activitat>
        <id>task-004</id>
        <titol>Permet marcar les tasques com a fetes</titol>
        <descripcio>Afegir checkbox a index.html i actualitzar l'estat.</descripcio>
        <data >2025-04-18</data>
        <categoria>
            <nomCat>Formularis</nomCat>
            <color>#00cec9</color>
        </categoria>
        <prioritat tipus = "alta" >
                <nom>Alta</nom>
        </prioritat>
        <realitzada>false</realitzada>
        
    </activitat>
    <activitat>
        <id>task-005</id>
        <titol>Crea el gràfic amb Chart.js</titol>
        <descripcio>Mostrar les tasques fetes per mes en format bar chart.</descripcio>
        <data >2025-04-20</data>
        <categoria>
            <nomCat>Visualització</nomCat>
            <color>#fab1a0</color>
        </categoria>
        <prioritat tipus = "alta" >
                <nom>Alta</nom>
        </prioritat>
        <realitzada>false</realitzada>
        
    </activitat>  
</activitats>
